{% set name = "psmon" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/{{ version }}.tar.gz 
  sha256: fb76948a80e459df041456e5e3bc0276a298215a73fa1fc7a9b0b68bda697e94

build:
  skip: True  # [win or osx]
  noarch: python
  number: 17
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - pyqtgraph
    - pyzmq
    - numpy
    - matplotlib
    - ipython

about:
  home: https://github.com/slaclab/psmon
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Data visualization tool for LCLS'
  description: |
    psmon is a remote and local data
    visualization tool used at LCLS for online
    analysis/monitoring developed originally to
    work with LCLS psana analysis framework.
    ZeroMQ is used as the data trasport layer
    and it provides two different rendering
    clients based on matplotlib and pyqtgraph.
  doc_url: https://github.com/slaclab/psmon
  dev_url: https://github.com/slaclab/psmon

extra:
  recipe-maintainers:
    - valmar
    - chrisvam

